### ISSUE TITLE
[DOCS] Code example conflicts with code feature

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar-ui-qmarkdown#57] opened 2019-12-11 11:53 UTC
**Describe the bug**
 Code example conflicts with code feature

**To Reproduce**
1. Go to [q-markdown#Code](https://quasarframework.github.io/quasar-ui-qmarkdown/examples#Code)
2. See error

**Screenshots**
![immagine](https://user-images.githubusercontent.com/33943143/70619341-25114080-1c15-11ea-9910-be5c8d56cfb8.png)

**Comment by hawkeye64** [comment] 2019-12-11 20:39
@heartbeatLV Sorry, just came off of a long burn with QCalendar and having issue switching gears. Can you tell me what the issue is, since I am not putting all the dots together.

Looks like the bottom example is missing the closing 3 backticks -- but not sure about first one, or exactly what the code conflict is...

**Comment by heartbeatLV** [comment] 2019-12-12 08:44
The `code example` in the template tab conflicts with the `code functionality`.

The example is shown using the 3 backticks, but the 3 backticks are also used for the code functionality

**Comment by hawkeye64** [comment] 2019-12-12 18:15
@heartbeatLV ummm, right -- I see that now. A bit of a conundrum this one...

**Comment by hawkeye64** [comment] 2020-01-05 21:19
I am not sure if this is fixable. Basically, chicken-and-egg scenario. Use mardown to show markdown is going to have some issues. unfortunately.

**Comment by hawkeye64** [comment] 2020-01-06 23:18
I will likely have to put a comment on that one. Let me know if you see others.

**Comment by hawkeye64** [comment] 2021-11-13 17:26
Closing as it's been over a year since last entry

**Closed by hawkeye64** 2021-11-13 17:26 UTC
